/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./src/components/common/AppCard.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    BaseButton: typeof import('./src/components/common/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/common/BaseInput.vue')['default']
    BaseModal: typeof import('./src/components/common/BaseModal.vue')['default']
    BasePagination: typeof import('./src/components/common/BasePagination.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    DataTableWrapper: typeof import('./src/components/common/DataTableWrapper.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    FormActions: typeof import('./src/components/common/FormActions.vue')['default']
    LoadingState: typeof import('./src/components/common/LoadingState.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    ResetButton: typeof import('./src/components/resuable/ResetButton.vue')['default']
    RichTextEditor: typeof import('./src/components/common/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchButton: typeof import('./src/components/resuable/SearchButton.vue')['default']
    SearchFilterBar: typeof import('./src/components/common/SearchFilterBar.vue')['default']
    StatusBadge: typeof import('./src/components/common/StatusBadge.vue')['default']
  }
}
